### ISSUE TITLE
Error on import

### ISSUE THREAD

**Issue by Alerovere** [tsutterley/pyTMD#106]
Hello, just to let you know that, installing from conda and trying to run the "Plot Tidal Forecasts at a Location" example, the  pyTMD.tools module is not found.
Trying to troubleshoot now, but I am not sure what to do.

**Comment by tsutterley** [comment]
Hi @Alerovere, great point. I never included that module in the package initialization. I think I have a fix for you in #107.

**Comment by Alerovere** [comment]
Thanks! I'll give it a try when I will have time again. Nice tool!
