### ISSUE TITLE
Compute tidal currents - variale referenced before assignment

### ISSUE THREAD

**Issue by RGFell** [tsutterley/pyTMD#112]
Hi all,

I'm trying to obtain the u and v components of the tidal current at a fixed point from the attached CSV file. But after I run compute_tidal_current.py as follows:

```
compute_tidal_currents.py erebus_2017_2019_hourly.csv erebus_current.csv --tide 'CATS2008' --directory /home/UOCNT/rag110/ --variables y x time --header 1 --type 'drift' -projection 4326
```
I got this error. I tried to trace it and see if I made something wrong but could not find anything so far. Maybe my call to the program is wrong?

```
Traceback (most recent call last):
  File "/home/UOCNT/rag110/anaconda3/envs/pytmd-env/bin/compute_tidal_currents.py", line 515, in <module>
    main()
  File "/home/UOCNT/rag110/anaconda3/envs/pytmd-env/bin/compute_tidal_currents.py", line 503, in main
    compute_tidal_currents(args.directory, args.infile, args.outfile,
  File "/home/UOCNT/rag110/anaconda3/envs/pytmd-env/bin/compute_tidal_currents.py", line 244, in compute_tidal_currents
    dinput = pyTMD.spatial.from_ascii(input_file, columns=VARIABLES,
  File "/home/UOCNT/rag110/anaconda3/envs/pytmd-env/lib/python3.9/site-packages/pyTMD/spatial.py", line 160, in from_ascii
    for i,line in enumerate(file_contents[header:]):
UnboundLocalError: local variable 'header' referenced before assignment
```

Thanks for your help.

[erebus_2017_2019_hourly.csv](https://github.com/tsutterley/pyTMD/files/9694101/erebus_2017_2019_hourly.csv)

**Comment by tsutterley** [comment]
Hi @RGFell,
Some of these were fixed prior but I haven't made an update to conda forge (which I will do today).

But I also needed to make some updates so that you could read ISO formatted dates from ascii files. These updates are in #113.

You should (once I merge this and put together the pypi+conda forge release) be able to run this as
```
compute_tidal_currents.py --tide 'CATS2008' --directory /home/UOCNT/rag110/ \
    --variables y x time --header 1 --type 'drift' --projection 4326 \
    --standard datetime --extrapolate erebus_2017_2019_hourly.csv erebus_current.csv 
```
[erebus_current.csv](https://github.com/tsutterley/pyTMD/files/9700242/erebus_current.csv)

**Comment by RGFell** [comment]
Excellent!, thanks very much for the help.
