### ISSUE TITLE
calc_astrol_longitudes.py: inconsistency between ASTRO5 and MEEUS solar perigee definition.

### ISSUE THREAD

**Issue by eapuntel** [tsutterley/pyTMD#117]
Hi there @tsutterley... I noticed a divergence between two definitions on calc_astrol_longitudes.py: equations are identical, but ASTRO5 has T defined in days and MEEUS uses T in centuries.

`if MEEUS:`
`    # convert from MJD to days relative to 2000-01-01T12:00:00`
`    T = MJD - 51544.5`
`   #...`
`    # mean longitude of solar perigee (Simon et al., 1994)`
`    PP = 282.94 + 1.7192 * T`

`elif ASTRO5:`
`    # convert from MJD to centuries relative to 2000-01-01T12:00:00`
`    T = (MJD - 51544.5)/36525.0`
`    # ...`
`    # mean longitude of solar perigee (Simon et al., 1994)`
`    PP = 282.94 + 1.7192 * T`

**Comment by tsutterley** [comment]
Hi @eapuntel. You're absolutely right the rate was in the incorrect units. I have this fix (and a documentation build fix) in #118
