### ISSUE TITLE
TypeError: combine_atlas_model() got an unexpected keyword argument 'variable'

### ISSUE THREAD

**Issue by robbibt** [tsutterley/pyTMD#119]
Hi @tsutterley, I've been getting this error when trying to model tides using TPXO8-atlas on 1.1.1:

```
~/Robbi/dea-notebooks/Frequently_used_code/../Tools/dea_tools/coastal.py in model_tides(x, y, time, model, directory, epsg, method, extrapolate, cutoff)
    792     # Read tidal constants and interpolate to grid points
    793     if model.format in ("OTIS", "ATLAS"):
--> 794         amp, ph, D, c = extract_tidal_constants(
    795             lon,
    796             lat,

/env/lib/python3.8/site-packages/pyTMD/read_tide_model.py in extract_tidal_constants(ilon, ilat, grid_file, model_file, EPSG, **kwargs)
    318             if (kwargs['grid'] == 'ATLAS'):
    319                 z0,zlocal = read_atlas_elevation(model_file, i, c)
--> 320                 xi,yi,z = combine_atlas_model(x0, y0, z0, pmask, zlocal,
    321                     variable='z')
    322             elif (kwargs['grid'] == 'ESR'):

TypeError: combine_atlas_model() got an unexpected keyword argument 'variable'
```

This only occurs in versions > 1.0.6. I think it may be because the `extract_tidal_constants` code here passes a lowercase `variable` param to the `combine_atlas_model` func:
https://github.com/tsutterley/pyTMD/blob/main/pyTMD/read_tide_model.py#L330-L331
https://github.com/tsutterley/pyTMD/blob/main/pyTMD/read_tide_model.py#L399-L400
https://github.com/tsutterley/pyTMD/blob/main/pyTMD/read_tide_model.py#L465-L466

But `combine_atlas_model` actually accepts an all-caps param `VARIABLE`:
https://github.com/tsutterley/pyTMD/blob/main/pyTMD/read_tide_model.py#L1259

(it's correctly passed here: https://github.com/tsutterley/pyTMD/blob/main/pyTMD/read_tide_model.py#L211)

**Comment by tsutterley** [comment]
Yep this is a bug from when I tried to address #100. I'll fix it today.

**Comment by tsutterley** [comment]
Thanks for catching it!

**Comment by tsutterley** [comment]
Hopefully everything's good now @robbibt. Let me know if you have any more problems. I'll put together a new release tomorrow so that these fixes are on pypi and conda-forge. thanks again!

**Comment by robbibt** [comment]
Winner, thankyou! Looking forward to updating to the latest version 😃
