### ISSUE TITLE
Can't reshape array of data file in plot tide forecasts #123

### ISSUE THREAD

**Issue by lyriselshylia** [tsutterley/pyTMD#128]
Hi @tsutterley, i got this error when trying to run [pyTMD](https://github.com/tsutterley/pyTMD)/[notebooks](https://github.com/tsutterley/pyTMD/tree/main/notebooks)/Plot Tide Forecasts.ipynb

```
ValueError                                Traceback (most recent call last)
Cell In [7], line 23
     21 # read tidal constants and interpolate to leaflet points
     22 if model.format in ('OTIS','ATLAS','ESR'):
---> 23     amp,ph,D,c = extract_tidal_constants(np.atleast_1d(LON),
     24         np.atleast_1d(LAT), model.grid_file, model.model_file,
     25         model.projection, type=model.type, method='spline',
     26         extrapolate=True, grid=model.format)
     27     DELTAT = np.zeros_like(tide_time)
     28 elif (model.format == 'netcdf'):

File c:\users\admin\appdata\local\programs\python\python39\lib\site-packages\pyTMD\read_tide_model.py:219, in extract_tidal_constants(ilon, ilat, grid_file, model_file, EPSG, **kwargs)
    216     xi,yi,hz,mz,sf = read_netcdf_grid(grid_file)
    217 else:
    218     # if reading a single OTIS solution
--> 219     xi,yi,hz,mz,iob,dt = read_tide_grid(grid_file)
    220 # invert tide mask to be True for invalid points
    221 mz = np.logical_not(mz).astype(mz.dtype)

File c:\users\admin\appdata\local\programs\python\python39\lib\site-packages\pyTMD\read_tide_model.py:640, in read_tide_grid(input_file)
    638 else:
    639     fid.seek(8,1)
--> 640     iob=np.fromfile(fid, dtype=np.dtype('>i4'), count=2*nob).reshape(nob,2)
    641     fid.seek(8,1)
    642 # read hz matrix

ValueError: cannot reshape array of size 1377962 into shape (1768185716,2)
```

At first i got some error from reading the data file name in the first place, as each model requires a different file format, which i managed to negate by changing the data file name (and zipping) accordingly to what the model required. After then, this problem appears.

Thanks in advance.

**Comment by tsutterley** [comment]
Hi @lyriselshylia,
sorry for the delay.
For TPXO9.1, I have this directory structure as the default for TPXO9.1:
- `TPXO9.1/DATA/grid_tpxo9`
- `TPXO9.1/DATA/h_tpxo9.v1`
- `TPXO9.1/DATA/u_tpxo9.v1`

I just ran the forecasting notebook to double check that things are working (as far as I can tell things are okay).
You don't have to gzip the individual files (uncheck the box in the notebook).

**Comment by lyriselshylia** [comment]
Sorry for the late reply. I've tried to uncheck the box and not gzip it instead, and it worked well. Thank you for checking it out!
