### ISSUE TITLE
AtributeError running compute_tidal_currents.py

### ISSUE THREAD

**Issue by carlosmry** [tsutterley/pyTMD#140]
Hi! 

I am trying to run the compute_tidal_currents.py script to get the tidal components from TPXO9-atlas-v5. However, I am getting the following error message:

... line 430, in arguments
    choices = sorted(pyTMD.io.model.ocean_current())
AttributeError: module 'pyTMD' has no attribute 'io'

Any thoughts on how to solve this?

Thanks!

**Comment by tsutterley** [comment]
hi @carlosmry!
I've been refactoring the code over the holiday. The `model` module should now be under `io` (as of yesterday). Maybe there's an old version in your environment somewhere?

**Comment by tsutterley** [comment]
I could move that class back out of `io` in the PR I'm working on. Let me think about it

**Comment by tsutterley** [comment]
I think at this point `model` is staying in `io. I'm going to close the issue. Hope you have everything sorted :)
