### ISSUE TITLE
pyTMD without Jupyter

### ISSUE THREAD

**Issue by bjarnebuchmann** [tsutterley/pyTMD#156]
I'm running pyTMD under Linux, but I do not want to install Jupyter packages. I have no intentions of using Jupyter on this system, and the packages would only bloat the installation. 
The "scripts" part of pyTMD seem to work fine without Jupyter, but every time I run a script, I get warnings:

```
/home/bjb/pyTDM/install-2023-01-31/lib/python3.10/site-packages/pyTMD-2.0.1.dev8+g664d6c0.d20230131-py3.10.egg/pyTMD/tools.py:54: ImportWarning: ipyleaflet not available
  warnings.warn("ipyleaflet not available", ImportWarning)
/home/bjb/pyTDM/install-2023-01-31/lib/python3.10/site-packages/pyTMD-2.0.1.dev8+g664d6c0.d20230131-py3.10.egg/pyTMD/tools.py:59: ImportWarning: ipywidgets not available
  warnings.warn("ipywidgets not available", ImportWarning)
```

Would it be possible to silence these warnings? If nothing else, then with an option stating that I am aware that the packages are not installed.

Thanks,
/Bjarne

**Comment by bjarnebuchmann** [comment]
I see that this issue has already been raised in https://github.com/tsutterley/pyTMD/discussions/94
However, my question is not so much about installation as spurious runtime warnings.

**Comment by tsutterley** [comment]
The import warnings have been changed to debug level logs. Should get rid of them unless running in debug mode
