### ISSUE TITLE
 pyTMD.io.model not working for current with FES2014 

### ISSUE THREAD

**Issue by lgostiau** [tsutterley/pyTMD#184]
Hello,

Thanks for this fantastic library.

Trying to load velocity data from FES2014 using :
```
model = pyTMD.io.model('/data/DATASETS/FES2014/',
    format='netcdf',
    compressed=False
   ).current('FES2014')
```
Leads to an error line 1232 in io/model.py

I had to modify the code to get it working properly : 
```
            for key,val in model_directory.items():                                                                                                                                                                
                self.model_directory = os.path.expanduser(model_directory[key])                                                                                                                                    
                self.model_file[key] = self.pathfinder(val)                                                                                                                                                        
```

adding the missing `[key]` argument to  `os.path.expanduser(model_directory)`

Then it works fine.

**Comment by tsutterley** [comment]
Thanks @lgostiau, I saw this earlier this week when I added the HAMTIDE model. This is fixed in main, and I will get a release out soon :+1:

**Comment by tsutterley** [comment]
This should be fixed on the current release 👍 let me know if you have any more trouble

**Comment by lgostiau** [comment]
Hello Tyler, 
Works perfectly, thanks a lot !
LG
