### ISSUE TITLE
setting directory and model 

### ISSUE THREAD

**Issue by Mohammad-Mardini** [tsutterley/pyTMD#202]
Hi Tyler,

I managed to install pyTMD on my MacBook. Now, I'm trying to run the first tutorial to  calculate the tidal displacements for a given location. Importing the modules went fine. However, I can't make it through the  `TMDwidgets = pyTMD.tools.widgets()` I keep getting an error as below:

`TraitError: The 'value' trait of a Text instance expected a unicode string, not the PosixPath PosixPath('/Users/mohammad/Documents/GitHub/pyTMD-main').`

I appreciate any help from your side to overcome this problem.

**Comment by tsutterley** [comment]
Hi @Mohammad-Mardini,
Yeah, looks like I was a little overambitious with the conversion to `pathlib`. Sorry about that! This is fixed in #203
Thanks for pointing it out!
Cheers,
Tyler

**Comment by Mohammad-Mardini** [comment]
Hi Tyler,

Thank you for help. The problem is solved now :) However, I'm having another error please see the attached screenshot. I think there is some gird/data missing! If this is the cause of the problem, could you please point me it. Thanks again for your time and efforts. 


<img width="1273" alt="Screen Shot 2023-05-22 at 7 30 16 AM" src="https://github.com/tsutterley/pyTMD/assets/35367221/780ea051-a6b9-4c41-9931-b645a028d14e">

**Comment by tsutterley** [comment]
Hi @Mohammad-Mardini!
Glad the first set of errors got fixed! 
So I'm not the producer of the tide constituents and am only licensed as an academic data user. The [`aviso_fes_tides.py`](https://github.com/tsutterley/pyTMD/blob/main/scripts/aviso_fes_tides.py) script _should_ be able to get the files you need to run with the FES models. You'll need to register with AVISO to get access. If you have any trouble let me know. I'll work on some documentation to highlight this.
Cheers,
Tyler

**Comment by tsutterley** [comment]
Hi @Mohammad-Mardini,
Glad the first set of errors got fixed! 
So I'm not the producer of the tide constituents and am only licensed as an academic data user. The [`aviso_fes_tides.py`](https://github.com/tsutterley/pyTMD/blob/main/scripts/aviso_fes_tides.py) script _should_ be able to get the files you need to run with the FES models. You'll need to register with AVISO to get access. If you have any trouble let me know. I'll work on some documentation to highlight this (including a step-by-step guide for getting data for the different models).
Cheers,
Tyler

**Comment by Mohammad-Mardini** [comment]
Hi @tsutterley,

Thank you for your prompt reply. Ok, I have registered to AVISO. Then I tried to run the [aviso_fes_tides.py](https://github.com/tsutterley/pyTMD/blob/main/scripts/aviso_fes_tides.py), using the credentials given by [aviso_fes_tides.py](https://www.aviso.altimetry.fr/en/home.html), by simply `python aviso_fes_tides.py`.  Note, the [script folder](https://github.com/tsutterley/pyTMD/tree/main/scripts) is under the main directory of pyTMD. But I got the a new error.  Please see the attached screenshot.

Best regards,
Mohammad


<img width="1681" alt="Screenshot 2023-05-22 at 9 04 37 AM" src="https://github.com/tsutterley/pyTMD/assets/35367221/abb7a7a2-c393-40dd-8f55-a218dc89c578">

**Comment by tsutterley** [comment]
Ok, great to know! I'll figure it out tomorrow and will let you know when I have a fix.

**Comment by tsutterley** [comment]
Hey @Mohammad-Mardini,
I tried replicating this error on a few different machines (one linux and one mac) but couldn't seem to make things break. I'll keep trying. I'm wondering if there was an IO error during the transfer.

**Comment by Mohammad-Mardini** [comment]
Hi @tsutterley,

Thank you for your time and efforts. What do you suggest to check if the IO error indeed occurring during the data transfer?

-Mohammad

**Comment by tsutterley** [comment]
Try running the program again?

**Comment by Mohammad-Mardini** [comment]
I'm running it since 5 mins, no errors! But it seems stuck at after printing `INFO:__main__:ftp://ftp-access.aviso.altimetry.fr/auxiliary/tide_model/fes2014_elevations_and_load/fes2014b_elevations/ocean_tide.tar.xz -->`


Is this normal?

**Comment by tsutterley** [comment]
Normal as it's a 2GB tar file and transfer rates aren't great. It should (eventually) load that tar file into memory (never downloading it to disk), then write out the individual netCDF files for each FES model constituent to the output directory you entered.

**Comment by Mohammad-Mardini** [comment]
I see! 🤞🤞 for good news soon!

**Comment by Mohammad-Mardini** [comment]
Unfortunately, it broke with a timeout error message :(

<img width="647" alt="Screenshot 2023-05-23 at 9 08 13 AM" src="https://github.com/tsutterley/pyTMD/assets/35367221/da2cc35f-9dce-46e2-ad8a-81ad302bd76f">

**Comment by tsutterley** [comment]
Okay. I'm adding an option for upping the timeout in #205. You should be able to force it to just download by making it big enough.

**Comment by Mohammad-Mardini** [comment]
I don't know how naive my question is, but, can you upload the required data/files to a Google drive foe example?

**Comment by tsutterley** [comment]
Sure. Uploading here. https://drive.google.com/drive/folders/1LVMMtqHb5AIBOivDnbxe7NM4Hi22-fDo

**Comment by Mohammad-Mardini** [comment]
Thank you, I downloaded them :) However, the original error is not solved yet. 


`FileNotFoundError: [PosixPath('GOT4.10c/grids_oceantide/q1.d'), PosixPath('GOT4.10c/grids_oceantide/o1.d'), PosixPath('GOT4.10c/grids_oceantide/p1.d'), PosixPath('GOT4.10c/grids_oceantide/k1.d'), PosixPath('GOT4.10c/grids_oceantide/n2.d'), PosixPath('GOT4.10c/grids_oceantide/m2.d'), PosixPath('GOT4.10c/grids_oceantide/s2.d'), PosixPath('GOT4.10c/grids_oceantide/k2.d'), PosixPath('GOT4.10c/grids_oceantide/s1.d'), PosixPath('GOT4.10c/grids_oceantide/m4.d')]`

**Comment by Mohammad-Mardini** [comment]
Thank you Tyler. It is working now. If you don't mind I will close this issue!

**Comment by tsutterley** [comment]
Glad we got everything sorted out! Let me know if you need anything :)
