### ISSUE TITLE
FES2012 support?

### ISSUE THREAD

**Issue by robbibt** [tsutterley/pyTMD#211]
Hi @tsutterley - I can see that `pyTMD` supports downloading FES2012 files here: https://github.com/tsutterley/pyTMD/blob/main/scripts/aviso_fes_tides.py#L129-L133

But FES2012 doesn't seem to be on the list of supported models here:
https://pytmd.readthedocs.io/en/latest/getting_started/Getting-Started.html#directories
![image](https://github.com/tsutterley/pyTMD/assets/17680388/21c9312e-2598-450e-885a-170bc9fc70d6)

Is modelling tide heights with FES2012 currently supported by `pyTMD`? If so, what directory structure and model name should I use to use that model?

**Comment by tsutterley** [comment]
Hey @robbibt,
I never knew if people would want to use the earlier models :)
I put in PR #212 to get things up to speed to running FES2012. I had to fix some variable names, and fix that the `eps2` constituent is named `e2` in FES2012. Using these parameters in a model definition file should let you use the 2012 model. I checked the outputs using one of the notebooks.
```
format      FES
name        FES2012
model_file  fes2012/*_FES2012_SLEV.nc.gz
type        z
version     FES2012
variable    tide_ocean
scale     0.01
compressed  True
reference   https://www.aviso.altimetry.fr/en/data/products/auxiliary-products/global-tide-fes.html
```

**Comment by robbibt** [comment]
We didn't realise we would need the earlier models either, but we have some areas along the Australian coastline where FES2014 unfortunately performs really poorly compared to FES2012; there's a neat paper here:
https://www.mdpi.com/2072-4292/11/10/1211
![image](https://github.com/tsutterley/pyTMD/assets/17680388/b6d10480-a91f-4f50-8df4-8647cbace025)

Thanks so much for this update - I think this will give us a much-needed nudge to finally update to pyTMD > 2.0!

**Comment by robbibt** [comment]
Hey @tsutterley, I've been able to generate some FES2012 tides using the model definition approach above (modifying it slightly to run on the uncompressed files) - thanks so much for this!

A related question: is there any way to essentially bypass the requirement for reading in an external definition file by declaring the parameters in the file in Python code? I noticed that `pyTMD.io.model(...)` seems to accept most of the params defined in the definition file - should I be able to just populate it with the content from the definition file directly? (I guess I could always write out the definition file on-the-fly when my code is run, but that feels a little clunky...).

**Comment by tsutterley** [comment]
Great! That's a major improvement!
I've actually been thinking about the subject of your related question lately. The definition files aren't my favorite solution. I think having the parameters be able to be entered as `kwargs` might be a nice way of generalizing the `model` class. It should also (hopefully) require less overall upkeep. I'll work on it :+1:
