### ISSUE TITLE
module 'pyTMD' has no attribute 'compute'

### ISSUE THREAD

**Issue by maucollu** [tsutterley/pyTMD#293]
Hi,
I fell I am missing something basic here.
I was trying to use the example given in [here](https://pytmd.readthedocs.io/en/latest/getting_started/Getting-Started.html#programs), i.e.:
`tide_h = pyTMD.compute.tide_elevations(x, y, delta_time,
    DIRECTORY=path_to_tide_models,
    MODEL='CATS2008', EPSG=3031, EPOCH=(2000,1,1,0,0,0),
    TYPE='drift', TIME='GPS',
    METHOD='spline', FILL_VALUE=np.nan)`

But, after I receive the error:
`AttributeError: module 'pyTMD' has no attribute 'compute'

What I have done:
- created a separate conda environment
- installed with conda the pyTMD package (`conda install -c conda-forge pytmd`)
- Run the following script:
`import numpy as np
import pyTMD

x                   = 14.5625
y                   = 36.4375
delta_time          = pyTMD.time.convert_calendar_dates(2000, 1, 1, minute = np.arange(0,24*60,30))
path_to_tide_models = 'D:\TPXO9\TPXO9_atlas\TPXO9_atlas_v5'
model_name          = 'TPXO9-atlas-v5'
epoch_tuple         = (1992,1,1,0,0,0)
tide_h = pyTMD.compute.tide_elevations(x, y, delta_time,
    DIRECTORY   = path_to_tide_models,
    MODEL       = model_name,
    EPOCH       = epoch_tuple,
    TYPE='drift', TIME='GPS',
    METHOD='spline', FILL_VALUE=np.nan)`

Can you please help?

**Comment by tsutterley** [comment]
Sorry about that @maucollu! I need to make a new release as I've refactored some things since `v2.1.0`. I've been working on some things that I was hoping to get in before `v2.1.1`.
In the mean time, can use the stable documentation :point_down: 
https://pytmd.readthedocs.io/en/stable/getting_started/Getting-Started.html

**Comment by maucollu** [comment]
Thanks a lot @tsutterley for the quick answer, no problem!
I have another doubt, though, but I'll post it in another separate issue.
Many thanks!
