### ISSUE TITLE
CATS2008 compute_tidal_elevations.py AttributeError: 'model' object has no attribute 'minor'

### ISSUE THREAD

**Issue by suzannelbevan** [tsutterley/pyTMD#320]
Hi tsutterley,

I have been able to successfully use CATS2008 with pyTMD.compute.tide_elevations, but running the compute_tidal_elevations.py gives me the error AttributeError: 'model' object has no attribute 'minor'.

e.g.
python compute_tidal_elevations.py --directory /mnt/raid1/suzanne/ripice --tide CATS2008-v2023 --format geotiff --projection 3031 --type grid  in.tif out.tif

I have also tried with CATS2008_V2023

Sorry I'm only a python beginner so may be doing something basic wrong.

Thanks, Suzanne

**Comment by suzannelbevan** [comment]
PS I see I can comment out line 340 to avoid the error.

**Comment by tsutterley** [comment]
Have you installed pyTMD before? The `minor` attribute is super new and only in the "bleeding edge".

**Comment by suzannelbevan** [comment]
Hi, thanks for getting back. I've only just started to use it pyTMD so not downloaded before. I'm trying to find an alternative to using Matlab to implement a tidal correction. Ideally to work on grid files.
If it's ok to just comment out the minor constituents bit I am happy to go with that.

Dr Suzanne Bevan
Geography Dept
Swansea University
Singleton Park
Swansea SA2 8PP
01792 602375
________________________________

**Comment by tsutterley** [comment]
That works fine. I can't currently recreate this error, but I'll try to track it down.

**Comment by tsutterley** [comment]
if you check the version, what do you get?
```
>>> import pyTMD
>>> pyTMD.version.version
'2.1.5.dev1+g4275e2d'
```

**Comment by suzannelbevan** [comment]
Sorry for the delay. I have version 2.1.4

**Comment by tsutterley** [comment]
Ok! Yes, this is likely a version conflict issue (running a newer version of `compute_tidal_elevations.py` than the installed package). It should hopefully run smoothly if you run:
```
compute_tidal_elevations.py --directory /mnt/raid1/suzanne/ripice --tide CATS2008-v2023 --format geotiff --projection 3031 --type grid in.tif out.tif
```
(no python in the beginning)
This would run the executable version that is installed with the package.

**Comment by suzannelbevan** [comment]
thank you, I will try that tomorrow. A second issue I had was needing to change the default geotiff driver in spatial.py from cog to GTiff. Is it possible to supply this via the call to compute_tidal_elevations.py?

**Comment by tsutterley** [comment]
Sure, I exposed that in #321. Note that now you need to use `--format GTiff`

**Comment by suzannelbevan** [comment]
Using compute_tidal_elevations.py without 'python' worked fine.
But then, to access --format GTiff option I reinstalled (using pip) pyTMD. Am now unable to import it.

>>> import pyTMD
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/suzanne/.local/lib/python3.10/site-packages/pyTMD/__init__.py", line 16, in <module>
    import pyTMD.compute
  File "/home/suzanne/.local/lib/python3.10/site-packages/pyTMD/compute.py", line 122, in <module>
    import pyTMD.io
  File "/home/suzanne/.local/lib/python3.10/site-packages/pyTMD/io/__init__.py", line 4, in <module>
    from .ATLAS import *
  File "/home/suzanne/.local/lib/python3.10/site-packages/pyTMD/io/ATLAS.py", line 107, in <module>
    import pyTMD.interpolate
  File "/home/suzanne/.local/lib/python3.10/site-packages/pyTMD/interpolate.py", line 23, in <module>
    import pyTMD.spatial
  File "/home/suzanne/.local/lib/python3.10/site-packages/pyTMD/spatial.py", line 112, in <module>
    h5py = import_dependency('h5py')
  File "/home/suzanne/.local/lib/python3.10/site-packages/pyTMD/utilities.py", line 130, in import_dependency
    module = importlib.import_module(name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/lib/python3/dist-packages/h5py/__init__.py", line 21, in <module>
    from . import _debian_h5py_serial as _h5py
  File "/usr/lib/python3/dist-packages/h5py/_debian_h5py_serial/__init__.py", line 25, in <module>
    from . import _errors
  File "h5py/_debian_h5py_serial/_errors.pyx", line 1, in init h5py._debian_h5py_serial._errors
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

Thanks for your help and sorry if I am doing things wrong.

**Comment by suzannelbevan** [comment]
So now I can use GTiff with the git cloned version of compute_tidal_elevations.py, but which still has the model.minor error. OK because I can comment out line 342.

One other small issue, somehow pip install pyTMD upgraded numpy to version 2, which then doesn't allow pyTMD to be imported. Sorry for my inexperience with python and github.

Thanks for your help.

**Comment by tsutterley** [comment]
No worries! There's definitely a learning curve to python and GitHub. I haven't made a release yet so `pip` installing will currently only install the "stable" version (2.1.4). There's still a few additions I want to make before releasing a potential 2.1.5.

For now, I think you can install the "bleeding edge" version directly using
```
python3 -m pip install --user git+https://github.com/tsutterley/pyTMD.git
```
This will install the latest version directly from the GitHub repo.

**Comment by tsutterley** [comment]
I created a release (2.1.5) that should simplify your workflows (can now be directly installed with pip for the latest version).

**Comment by suzannelbevan** [comment]
That works great, thanks Tyler. I admit I'd not had much luck with getting the pre-release version of it.
