### ISSUE TITLE
pyTMD.tools.py has a bug

### ISSUE THREAD

**Issue by ZHANGGU** [tsutterley/pyTMD#338]
Installed development version

Run the example as below
![2024-09-12_09-47-44](https://github.com/user-attachments/assets/5e91536d-cad7-41c3-8a03-55cdde967f98)
![2024-09-12_09-48-24](https://github.com/user-attachments/assets/f58d0393-6d89-491f-9c00-4a097ae74f67)

from __future__ import print_function

import numpy as np
import matplotlib.pyplot as plt
import IPython.display

# import tide programs
import pyTMD.crs
import pyTMD.io
import pyTMD.time
import pyTMD.tools
# available model list
model_list = sorted(pyTMD.io.model.ocean_elevation())
# display widgets for setting directory and model
TMDwidgets = pyTMD.tools.widgets()
TMDwidgets.model.options = model_list
TMDwidgets.model.value = 'GOT4.10'
TMDwidgets.VBox([
    TMDwidgets.directory,
    TMDwidgets.model,
    TMDwidgets.atlas,
    TMDwidgets.compress
])

**Comment by tsutterley** [comment]
Hey @ZHANGGU,
In order to run the notebooks with leaflet maps you need the full installation. You can install `pyTMD` directly from conda-forge, or by including `[all]` with the `pip` installation. 

```
python -m pip install pyTMD[all]
```

**Comment by tsutterley** [comment]
That being said, I should update the documentation to clarify the requirements.

**Comment by tsutterley** [comment]
Oh a Windows build. I would recommend installing from conda. You need GDAL for the complete installation, which can be tricky to install.

**Comment by tsutterley** [comment]
I'm going to close this issue, feel free to reopen it.
