### ISSUE TITLE
pyTMD.tools.py has bug in the class leaflet from Conda installation

### ISSUE THREAD

**Issue by ZHANGGU** [tsutterley/pyTMD#339]
Conda installed and updated the pyTMD
after run the example, it seems there is a bug in int the tools.py. see error as screen shot

![2024-09-12_10-28-28](https://github.com/user-attachments/assets/cc1fe569-ff71-4019-8a2b-8ba718e30d61)

from __future__ import print_function

import os
import datetime
import numpy as np
import matplotlib.pyplot as plt
import IPython.display

# import tide programs
import pyTMD.io
import pyTMD.predict
import pyTMD.tools
import pyTMD.utilities
import timescale.time

# autoreload

# available model list
model_list = sorted(pyTMD.io.model.ocean_elevation())
# display widgets for setting directory and model
TMDwidgets = pyTMD.tools.widgets()
TMDwidgets.model.options = model_list
TMDwidgets.model.value = 'GOT4.10'
TMDwidgets.VBox([
    TMDwidgets.directory,
    TMDwidgets.model,
    TMDwidgets.atlas,
    TMDwidgets.compress,
    TMDwidgets.datepick
])
# default coordinates to use
LAT,LON = (32.86710263,-117.25750387)
m = pyTMD.tools.leaflet(center=(LAT,LON), zoom=12,
    zoom_control=True, marker_control=True)
# show map
m.map

**Comment by tsutterley** [comment]
see #338
