### ISSUE TITLE
Bounds not being calculated properly when `crop=True`

### ISSUE THREAD

**Issue by robbibt** [tsutterley/pyTMD#356]
While looking into #355, I noticed that `crop=True` didn't seem to be having any effect on run-times, unless `bounds=[...]` was also provided.

I have a feeling that the default `bounds` value here isn't being set correctly:
https://github.com/tsutterley/pyTMD/blob/main/pyTMD/io/FES.py#L230 

I believe the `kwargs.setdefault('bounds', [xmin, xmax, ymin, ymax])` call in `io.FES.extract_constants` is meant to return `[xmin, xmax, ymin, ymax]` if no bounds are provided. However, this default is only set if `bounds` is absent from `kwargs` completely. The issue is that `bounds` *does* exist in `kwargs`: it has a default value set to `None` here:
https://github.com/tsutterley/pyTMD/blob/main/pyTMD/io/model.py#L1001
```
>>> print(kwargs)
{'version': 'EOT20', 'scale': 0.01, 'compressed': False, 'type': 'z', 'crop': True, 'bounds': None, 'method': 'spline', 'extrapolate': True, 'cutoff': inf, 'append_node': False, 'apply_flexure': False}
```

So because `bounds` does exist in `kwargs`, the default `bounds` value is never set to `[xmin, xmax, ymin, ymax]` and remains `None` - which means this line never triggers:
https://github.com/tsutterley/pyTMD/blob/main/pyTMD/io/FES.py#L258
```
>>> print(kwargs['crop'] and np.any(kwargs['bounds']))
None
```

I've only tested `io.FES.extract_constants` on the latest `pyTMD==2.1.7`; not sure if this affects `io.FES.*constants` or the other `io` modules.

**Comment by tsutterley** [comment]
thanks @robbibt! fix is in #357

**Comment by robbibt** [comment]
Hey @tsutterley, looks like there's still some issues when setting `crop=True` via `from pyTMD.compute import tide_elevations`: `bounds` is passed as `None` here, and so it still ends up propagating down to `io.FES.extract_constants` and overriding `kwargs.setdefault('bounds', [xmin, xmax, ymin, ymax])`:
https://github.com/tsutterley/pyTMD/blob/main/pyTMD/compute.py#L362
```
{'version': 'FES2022', 'compressed': False, 'type': 'z', 'crop': True, 'bounds': None, 'method': 'spline', 'extrapolate': True, 'cutoff': inf, 'append_node': False, 'apply_flexure': False, 'scale': 0.01}
```

`**kwargs` possibly might need to be passed here too:
https://github.com/tsutterley/pyTMD/blob/main/pyTMD/compute.py#L361-L364

**Comment by tsutterley** [comment]
hopefully second time is the charm :sweat_smile:
