### ISSUE TITLE
Casting complex values to real discards the imaginary part

### ISSUE THREAD

**Issue by alexguyot** [tsutterley/pyTMD#44]
Hello,

First of all, thanks a lot for the tool ! 
I'm a new user of pyTMD and a novice in tidal prediction so please excuse me in advance if my question is not clear.

I'm using the FS2014 model (`fes2014/ocean_tide` data) to predict tide elevation at 1 specific location and for 1 specific datetime.
The obtained prediction results look good (and relatively close (~10cm) to local tide charts).

However, during the `extract_FES_constants`, a python warning is raised :

> venv/lib/python3.7/site-packages/numpy/ma/core.py:462: ComplexWarning: Casting complex values to real discards the imaginary part
  fill_value = np.array(fill_value, copy=False, dtype=ndtype)

I'm not sure how to handle this.
How to fix it ? Should I worry about the quality of the prediction ?

Many thanks,
Alexandre

**Comment by tsutterley** [comment]
hi @alexguyot 
Thanks for pointing this out.  It's a scary warning but harmless in this case.  It pops up when calculating the amplitudes from the complex form of the constituent.  I had the absolute value being calculated on the masked arrays and not the data of the masked arrays.  numpy was flagging that the fill values on the masked arrays were losing their complex component.  I put in PR #45 which should fix the underlying problem.  Let me know how it goes.
-ts

**Comment by alexguyot** [comment]
Hi @tsutterley,
Works perfectly !
Thanks a lot for the support.
Alexandre
