### ISSUE TITLE
Wrong unit in extrapolate

### ISSUE THREAD

**Issue by DerLude** [tsutterley/pyTMD#55]
Hi,
first of all thanks for this great library. I'm new in working with ocean data and was quite surprised that apparently all the few other tidal prediction libraries out there seem to be outdated.

I think I've found a bug in your code. I've never uploaded something in Github, so I will just explain what I've found:
Your read_*_model.py modules have an option EXTRAPOLATE to predict tides where the models are undefined. In the code, there is a hardcoded upper bound of 10km for extrapolation. However, in nearest_extrap.py by default (EPSG=='4326'), the KDTree is build using carthesian coordinates [m]. Hence, on line 127, the tree.query is indeed cutoff after 10m, not 10km.

Moreover, I suggest to at least mention the hardcoded 10km cutoff in the header description of EXTRAPOLATE in read_*_model.py. Even better, this could be made an additional option...

Cheers,
Ludwig

**Comment by tsutterley** [comment]
Hi @DerLude,
You're absolutely right.  I forgot to change the ellipsoidal major axis to kilometers when converting to cartesian.  Putting in a PR now to fix this.
I also added options to set the cutoff distance (this was on my to-do list).  Thanks for giving me the push to actually get it done.
Cheers
