### ISSUE TITLE
Compute u and v velocities for TPXO9-atlas

### ISSUE THREAD

**Issue by aragong** [tsutterley/pyTMD#6]
Thank you for sharing this conversion of the TMD to python.

I think that extraction of velocities is not described in your codes but, Do you know if the code will work using velocities if I refer type=u and select the correct UV_* source files?

I need to extract TPXO9-atlas currents for spatial domains over months and I need some quick solution to do this in python.

Thank you in advance!

**Comment by tsutterley** [comment]
Hi @aragong.  That should be hopefully all you would have to do.   Similar to the matlab TMD package, using TYPE='u' will give you the tidal velocities in cm/s and TYPE='U' will give you the tidal transports in m^2/s.  I added a notebook ([Plot Antarctic Tidal Currents.ipynb](https://github.com/tsutterley/pyTMD/blob/master/Plot%20Antarctic%20Tidal%20Currents.ipynb)) showing an animation of tidal velocities around Antarctica which hopefully helps you on your way.

**Comment by aragong** [comment]
Hi @tsutterley, Thank you for adding those notebooks, I am waiting for access to download netCDF databases of TPXO (I used binary files in Matlab), I am sure it will be a great help. 

In my specific case, I want to obtain currents in CFSR_ocean grid (global grid) for a specific period of time (e.g. 1 month). Should I use predict_tide_drift() instead of predict_tide() for my specific case, shouldn't I? 

Than you for your time!
