### ISSUE TITLE
Plot Tide Forecasts notebook returns unexpected output for TPXO9-altas-v4?

### ISSUE THREAD

**Issue by bludka** [tsutterley/pyTMD#60]
Hi Tyler,
Thanks for making this tool for Python. I am new to both this tool and python, so I might be doing something wrong, but when I compare the output of the "Plot Tide Forecasts" notebook at the La Jolla Tide Gauge (default location) using the TPXO9-altas-v4 model (Svetlana Erofeeva gave me access to the model files via the box app), I get output that seems incorrect. I have tried this for a variety of dates and compared to two other versions of La Jolla Tide data:
This GUI: https://tidesandcurrents.noaa.gov/noaatidepredictions.html?id=9410230&units=metric&bdate=20210629&edate=20210706&timezone=GMT&clock=24hour&datum=MSL&interval=hilo&action=dailychart
and this netCDF dataset water_levels.nc : https://datadryad.org/stash/dataset/doi:10.5061/dryad.n5qb383
Any chance you also see an inconsistency / have ideas what could be going on?
Thanks for your help!
-Bonnie

**Comment by bludka** [comment]
Oh wow, thanks so much Tyler! I've been banging my head on this for a while and really glad I posted here. Really appreciate it!

**Comment by bludka** [comment]
Hi Tyler,
I downloaded the latest .zip file today
I think there still might be something funky going on here, even with the extrapolation fix: 
<img width="640" alt="Screen Shot 2021-07-11 at 4 38 04 PM" src="https://user-images.githubusercontent.com/28815558/125213240-70168e00-e266-11eb-8db2-eb9275a3fa20.png">

**Comment by tsutterley** [comment]
Hi @bludka, are you still having trouble?  Got an email last night but can't find your messages here.

**Comment by bludka** [comment]
Hi Tyler, 
Apologies, I think that was user error. Looks good now!
-Bonnie

**Comment by tsutterley** [comment]
Hi Bonnie,
Glad things worked out 😀
Tyler
