### ISSUE TITLE
Mask not set when extrapolating NetCDF

### ISSUE THREAD

**Issue by DerLude** [tsutterley/pyTMD#66]
I've found another issue related to the extrapolation:
In `read_netcdf_model.py`, the constituent NetCDFs do not include any information about invalid data (at least in  TPXO9-atlas-v4 as NetCDF.). For this reason, you derive a mask from the `grid_file` bathymetry and apply this to the values:
`#-- mask invalid values`
`z1.mask[:] |= np.copy(D.mask)`
However, if the value is invalid, `nearest_extrap` tries to extrapolate using the `z`-Grid, which has no appropriate mask. Hence, extrapolation always returns 0 for all constituents in my case. I suggest to apply a bathymetry mask to z as well. After line 212 in  `read_netcdf_model.py`:
`z.mask = bathymetry.mask`

**Comment by tsutterley** [comment]
Thanks @DerLude! I'll get this fixed tomorrow 👍

**Comment by tsutterley** [comment]
This is now fixed!  Thanks @DerLude
