### ISSUE TITLE
Longitude convention in tide models

### ISSUE THREAD

**Issue by DerLude** [tsutterley/pyTMD#75]
I have a tiny suggestion for a change in the code of `read_FES_model.py` (and maybe also for similar other read_XXX_model.py).

In short, I suggest to remove (at l.132ff)
```
    #-- adjust longitudinal convention of input latitude and longitude
    #-- to fit tide model convention
    if (np.min(ilon) < 0.0):
        lt0, = np.nonzero(ilon < 0)
        ilon[lt0] += 360.0
```
and replace it by (at l.163 )
```
    #-- adjust longitudinal convention of input latitude and longitude
    #-- to fit tide model convention
    if(np.max(lon)>180. and np.min(ilon)<0.):         # nc: [0 - 360], points: [-180 - 180]
        ilon[ilon<0.] += 360.
    elif(np.min(lon)<0. and np.max(ilon)>180.):       # nc: [-180 - 180], points: [0 - 360]
        ilon[ilon>180.] -= 360.
```
So, instead of assuming that all NC-grids are [0 - 360], it will check the input data and the points and convert the points accordingly.
Surely, the FES data comes as [0 - 360], so the previous code works fine. However, I work with a modified version (explained below), therefore I need these changes and suggest to include them in your version as well. 

My situation is as follows (sorry for the long text but I would like to explain why I ask for this change):

I want to calculate FES-tides for a few points. This is done nicely by pyTMD but it takes quite long (on my machine almost 2min for each call of extract_FES_constans). I have searched the code for what takes so long and found out that the reason is that pyTMD first reads the entire grids for all constituents into RAM before interpolating the specific point(s) data.
My first intention was that the code should maybe not read the entire grids if the requested point(s) are limited to a quite small area. However, I understand that interpolation/extrapolation needs at least a limited region around the point and if the points are located around the Greenwich meridian this can be quite complicated (I'm working with points in the North Sea).
Therefore I have another approach to solve this. I have extracted the region of northern Europe from the FES-NetCDFs to separate NCs, which are smaller and, hence, way faster to read (~5 sec). However, the is the problem with the Greenwich meridian. The original FES data longitudes range from 0°-360°. For northern Europe, this means that I need 355°-360° and 0°-30°. Extracting these two regions and joining them in a new NC causes makes Scipy.interpolate crash (`ValueError: The points in dimension 1 must be strictly ascending`). Therefore I converted the western hemisphere longitudes to negative values. My longitudes in the NCs are now -5°-30°. To work with such modified data, I need the modifications as suggested above. If you would include these changes, you would never have to care about longitude conventions any more.

**Comment by tsutterley** [comment]
Great idea.  PR #76 is in with your recommended changes.
